name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest

      - name: Build Docker image
        run: docker build -t simple-adder-image .

      - name: Run Docker container for verification
        run: |
          docker run simple-adder-image

  # A simple "deployment" step for demonstration purposes
  # This job will only run if the build-and-test job is successful
  simulate-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deployment notification
        run: echo "Successfully verified and 'deployed' the adder program."
